# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160509_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instance',
            field=models.CharField(blank=True, max_length=255, verbose_name='Instance URL'),
        ),
    ]
